spring:
  mail:
    #配置发送方协议
    protocol: smtp
    #配置smtp服务器地址
    host: smtp.sina.com
    #发送方的邮箱
    username: cookie_xzj@sina.com
    #发送方的密码
    password: 20170711xzj

dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://47.106.162.31:2181
  protocol:
    port: -1
  consumer:
    check: false
    timeout: 100000
    retries: 3
