server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///1903_spring
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://47.106.162.31:2181
  protocol:
    port: -1
  consumer:
    check: false
    timeout: 10000
    retries: 3
